name = "Havoc Minipack S1"
author = "minecraftbossdj, bigcrazyclaw"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d786cac4f6366f63b8b4cf3e043227dedfd855d046b99177b6238ab7239f4c17"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
