name = "Havoc Minipack S1"
author = "minecraftbossdj, bigcrazyclaw"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67d103a1ed4ca2095d881f448d4ddb87b844aea21da3754beb78df5cfe171977"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
