name = "Havoc Minipack S1"
author = "minecraftbossdj, bigcrazyclaw"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b001c6ebbb2991af05eaabc9d10c25034367149cef8a686f0bfa55518c5dc3f"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
