name = "Havoc Minipack S1"
author = "minecraftbossdj, bigcrazyclaw"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65e8327f82e3222f82fed3cb3042855c74cb26f74e69b6c2a3ef13ba642f11f0"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
