name = "Havoc Minipack S1"
author = "minecraftbossdj, bigcrazyclaw"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "450b369d6d6d985ea616a62e11af26ea5cc1401eb714c808b4d6350ecc26ae55"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
