name = "Havoc Minipack S1"
author = "minecraftbossdj, bigcrazyclaw"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08e469cad26393880e4b460a183d9e0639e2321b96ed1b398bea1b3584c1e2aa"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
